### ISSUE TITLE
Training example 2

### ISSUE THREAD

**Issue by buddhikaherath92-dev** [Developers-In/internal-training#1]
![Screenshot from 2020-09-11 08-55-00](https://user-images.githubusercontent.com/69967705/92852606-8b2d2d00-f40c-11ea-83ac-9d9d4b783941.png)

Do this layout using bootstrap 4, it does not have to be the same style, you can use your own colors and styles as you like. But try to stick with the layout

**Comment by LalithK90** [comment]
Code modification was done
